### ISSUE TITLE
vision transformer about object detection and instance segmentation

### ISSUE THREAD

**Issue by StephenZhao1** [bubbliiiing/segformer-pytorch#18]
Dear maintainer, wait for your more reimplementations on object detection and instance segmentation using transformer

**Comment by bubbliiiing** [comment]
which one。

**Comment by StephenZhao1** [comment]
object detection like DETR and deformable DETR, instance segmentation like mask2former and Mask Transfiner

**Comment by bubbliiiing** [comment]
I share a repo about DETR, but deformable DETR need C++ Code, sad.
maybe i will go to learn something about mask2former or Mask Transfiner.
But work is too large for me to relax and learn extra knowlage

**Comment by bubbliiiing** [comment]
tired, not large. hh

**Comment by StephenZhao1** [comment]
Great job!
