### ISSUE TITLE
修改CEloss函数为BCEloss，确保输入输出均为（N, 1）,报错维度不匹配

### ISSUE THREAD

**Issue by Buling-Knight** [bubbliiiing/segformer-pytorch#6]
UP主你好，非常感谢你公开的代码，对我帮助很大。
有一个问题想请教一下：我将自己的代码和报错信息截图，请您有空的话指点一下，非常感谢

我尝试修改CEloss为BCEWithLogitsLoss，确保输入尺寸输出尺寸shape相同，仍然报错。
注：我已将解码头输出由（b, 2, h, w）改为（b, 1, h, w）

![1](https://user-images.githubusercontent.com/91008145/201803574-b15c2a1e-d4d4-4bfe-b02d-260863a65841.jpg)
![2](https://user-images.githubusercontent.com/91008145/201803592-20ba0e33-11f5-4a
![3](https://user-images.githubusercontent.com/91008145/201803604-8337dcec-32da-4a0e-83d6-0efe5a2aa52c.jpg)
0b-b9ad-d828526678a5.jpg)

**Comment by Buling-Knight** [comment]
![2](https://user-images.githubusercontent.com/91008145/201803765-bbd7b69b-1635-40ac-a55a-5c1f81825edd.jpg)
这个是补充断点调试的信息。

**Comment by Buling-Knight** [comment]
weights参数设置的问题，抱歉打扰了昨晚调试调糊涂了

**Comment by bubbliiiing** [comment]
好的
